name: Publish to npmjs.org

on: push

jobs:
  do-the-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm run install:packages -- --ci
      - run: npm test
      - run: npm run publish:packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - uses: EndBug/add-and-commit@v7
